### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by Kielx** [Kielx/blog-cms#3]
List of stuff that needs to be done for me to consider the project done.

- [x] ~~Create a basic Node.js server which will host the whole application.~~ **(Done on 21.07.2020)**
- [x] ~~Start writing about stuff you learned / did to get in habit and practice writing.~~ **(Created my first blog post on 21.07.2020!)**
- [x] ~~Create a template with template engine (Pug).~~ **(Finished on 27.07.2020)**
  - ~~Create basic template~~
  - ~~Create a layout to inherit~~
  - ~~Create route that will work for dynamic posts~~
  - ~~Maybe add some styling~~
  - ~~Decide how to deal with names and links to posts~~ 
- [x] ~~Move posts to database **(Done 27.07.2020)**~~
- [x] ~~Make it possible to add / delete posts.~~ **(Done on 30.07.2020)**
  - ~~Create a form to add posts~~
  - ~~Create a way to delete posts~~ 
- [x] ~~Change view engine to handlebars~~ **(Abandoned this idea)**
- [x] ~~Add bootstrap~~ **(Done on 01.08.2020)**
- [x] ~~Add navbar~~ **(Done on 01.08.2020)**
- [x] ~~Add markdown styling to post content + added markdown editor~~ **(Done on 02.08.2020)**
- [x] ~~Set up routes for pages.~~ **(Done on 10.08.2020)**
- [x] ~~Rewrite the project to follow MVC principle~~  **(Done on 10.08.2020)**
- [x] ~~Rework the main file to follow the DRY rule~~ **(Done on 10.08.2020)**
- [x] ~~Create a way to update posts~~ **(Done on 04.08.2020)**
- [x] ~~Add authentication~~ **(Done, added user authentication with passport local strategy)
- [ ] Rewrite the project to use Bootstrap templates
- [ ] Add link to display all posts
- [ ] Add about me page
- [ ] Add working contact form
- [ ] Rewrite pug files to .ejs
- [ ] Create a working admin page
- [ ] Add necessary security measures
- [ ] Add forgot password
- [ ] Find some SMTP server?
- [ ] Start writing about stuff you do... again.
- [ ] Consider how to create secure routes to serve blog as an API

- [ ] Find a place and a way to deploy your blog somewhere.
- [ ] More...
